driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  chef_zero_port: 9010

platforms:
  - name: ubuntu-14.04
    driver:
      network:
      - ["private_network", {ip: "33.33.33.21"}]
  - name: ubuntu-16.04
    driver:
      network:
      - ["private_network", {ip: "33.33.33.22"}]
  - name: centos-6
    driver:
      network:
      - ["private_network", {ip: "33.33.33.25"}]
  - name: centos-7
    driver:
      network:
      - ["private_network", {ip: "33.33.33.28"}]

suites:
  - name: default
    run_list:
      - recipe[supermarket-omnibus-cookbook::default]
    attributes:
      supermarket_omnibus:
        chef_server_url: https://notarealserver.chef.io
        chef_oauth2_app_id: randomstring
        chef_oauth2_secret: randomstring
        chef_oauth2_verify_ssl: false
