---
driver:
  name: vagrant
  customize:
      memory: 512

provisioner:
  name: chef_zero
  chef_zero_port: 9010

platforms:
  - name: ubuntu-12.04
    driver:
      network:
      - ["private_network", {ip: "33.33.33.20"}]
  - name: ubuntu-14.04
    driver:
      network:
      - ["private_network", {ip: "33.33.33.21"}]
  - name: centos-5.11
    driver:
      network:
      - ["private_network", {ip: "33.33.33.24"}]
  - name: centos-6.7
    driver:
      network:
      - ["private_network", {ip: "33.33.33.25"}]
  - name: centos-7.1
    driver:
      network:
      - ["private_network", {ip: "33.33.33.28"}]

suites:
  - name: default
    run_list:
      - recipe[supermarket-omnibus-cookbook::default]
    attributes:
      supermarket_omnibus:
        chef_server_url: ~
        chef_oauth2_app_id: ~
        chef_oauth2_secret: ~
        chef_oauth2_verify_ssl: ~
