name             'supermarket-omnibus-cookbook'
maintainer       'Irving Popovetsky'
maintainer_email 'irving@chef.io'
license          'all_rights'
description      'Installs and Configures Supermarket from the Omnibus packages on packages.chef.io'
source_url       'https://github.com/irvingpop/supermarket-omnibus-cookbook'
issues_url       'https://github.com/irvingpop/supermarket-omnibus-cookbook/issues'
version          '1.4.1'

depends 'chef-ingredient', '>= 0.18.0'
depends 'hostsfile'
depends 'fancy_execute'
