name             'supermarket-omnibus-cookbook'
maintainer       'Irving Popovetsky'
maintainer_email 'irving@chef.io'
license          'Apache 2.0'
description      'Installs and Configures Supermarket from the Omnibus packages on packages.chef.io'
source_url       'https://github.com/irvingpop/supermarket-omnibus-cookbook'
issues_url       'https://github.com/irvingpop/supermarket-omnibus-cookbook/issues'
chef_version     '>= 12.1'
version          '2.0.0'

supports 'ubuntu'
supports 'redhat'
supports 'centos'

depends 'chef-ingredient', '>= 0.21.2'
depends 'compat_resource', '>= 12.14.3'
depends 'hostsfile'
depends 'fancy_execute'
